### PR TITLE
Be more specific about VERSION cutoff for keyword arg lowering change

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by chkwon** [comment]
Thanks! Now what should I do with the METADATA pull request? Should I tag another version?

**Comment by tkelman** [comment]
you can amend it in place if you'd like, see the attobot readme for instructions

**Comment by tkelman** [comment]
not critical though

**Comment by chkwon** [comment]
Great. Thanks. Attobot rocks!

**Pull request merged**
